import React from 'react'
import StaticPageLayout from '../../components/StaticPageLayout'

export default function AIExplainerPage() {
  return (
    <StaticPageLayout title="How Our AI Bank Statement Review Works">
      <h2>AI does the heavy lifting. Humans make the final call.</h2>
      <p>
        Taxly's core innovation is our proprietary AI engine that reviews your bank statements to find hidden deductions and ensure no income is missed. However, it's crucial to understand what our AI does—and just as importantly, what it <strong>doesn't</strong> do.
      </p>

      <h3>What the AI Does</h3>
      <ul>
        <li><strong>Parses Complex PDFs:</strong> Ingests raw bank statement PDFs and normalizes the transaction data cleanly.</li>
        <li><strong>Categorizes Transactions:</strong> Automatically labels transactions into buckets like salary, dividend, interest, and potential 80C/80D investments.</li>
        <li><strong>Flags Potential Deductions:</strong> If it sees a payment to "LIC India" or "Star Health", it flags this as a potential deduction.</li>
        <li><strong>Suggests with Confidence Scores:</strong> Provides the reviewing CA with a confidence score for each flagged item, along with exactly what proof (e.g., premium receipt) is required to claim it.</li>
      </ul>

      <h3>What the AI NEVER Does</h3>
      <ul>
        <li><strong>Never Auto-Claims:</strong> The AI cannot legally claim a deduction on its own. It only surfaces it for review.</li>
        <li><strong>Never Files Without Review:</strong> Every single XML generated by our system must be reviewed and signed off by a human Chartered Accountant before it is provided to you.</li>
        <li><strong>Never Replaces Professional Judgment:</strong> If an ambiguous transaction occurs, the AI flags it for human review rather than making a guess.</li>
      </ul>

      <h2>Why CAs Love This</h2>
      <p>
        By automating the tedious process of line-by-line bank statement review, we save CAs hours of manual data entry. Instead of searching for needles in a haystack, the CA acts as a highly-skilled verifier of the AI's flagged items, allowing them to focus on complex tax strategy and final verification.
      </p>
    </StaticPageLayout>
  )
}
